### ISSUE TITLE
Update `unicode-xid` to 0.2

### ISSUE THREAD

**Issue by cwfitzgerald** [mystor/synstructure#33]
I'm going through one of my projects trying to remove duplicate dependencies, and currently `synstructure`'s  `unicode-xid v0.1` dependency conflicts with `syn v1.0.5`'s `unicode-xid v0.2` dependency. This means `synstructure` can make a duplicate dependency all on it's own. I will try to make a PR updating this.

**Comment by mystor** [comment]
Fixed by #34
