### ISSUE TITLE
Unable to build systructure for 'wasm32-unknown-unknown' target

### ISSUE THREAD

**Issue by ffuugoo** [mystor/synstructure#36]
There is a project called [watt](https://github.com/dtolnay/watt), which provides tools to compile your proc macro implementation to WASM and then use this pre-compiled WASM binary (with watt-provided runtime) to perform actual proc macro expansion (instead of compiling proc macro for host on build).

I have a proc macro that is implemented using synstructure and I want to provide "wattified" version of my crate.

However, according to these two issues [[1]](https://github.com/rust-lang/rust/issues/52707) [[2]](https://github.com/rust-lang/cargo/issues/5825), `wasm32` target simply does not include `proc_macro` crate and so it's impossible to depend on it in any code that is compiled to WASM.

Synstructure depends on `proc_macro` unconditionally in `MacroResult` in `lib.rs`, so it makes impossible to build synstructure for `wasm32` target.

**Comment by icefoxen** [comment]
Seconded, more or less...  I think?  I have [a thing using webgl](https://github.com/ggez/ggraphics/tree/d6a8900de11c261c29796be1cc9ffc32c8099895) with `glow` and `web-sys` that builds fine for `wasm32` but using `synstructure` 0.12.1 it *used* to work... and a `cargo update` bumped `synstructure` to 0.12.2 and now it fails to load with missing wasm symbols.  And forcing it to use `synstructure` 0.12.1 makes it not build at all.  Sooooooo I have no idea what's happening or how to diagnose it further but `synstructure` seems to be the only thing that's changed.

**Comment by mystor** [comment]
Fixed by #37, and published as 0.12.3
