### ISSUE TITLE
syn/full required to parse const generics

### ISSUE THREAD

**Issue by nhynes** [mystor/synstructure#44]
Successfully parsing const generics is gated behind the `full` feature of syn. Here's an example of using syn with the features in the current Cargo.toml.

some-crate/main.rs:
```rust
#![allow(incomplete_features, unused)]
#![feature(const_generics)]

struct ConstGeneric<const N: usize>([u8; N]);

#[derive(mwe::Demo)]
struct Wrapper {
    inner: ConstGeneric<42>
}
```

mwe/lib.rs:
```rust
#[proc_macro_derive(Demo)]
pub fn derive_demo(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let s: syn::DeriveInput = syn::parse(input).unwrap();
    Default::default()
}
```

The error:
```
error: proc-macro derive panicked
 --> src/main.rs:6:10
  |
6 | #[derive(mwe::Demo)]
  |          ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Error("expected one of: `for`, parentheses, `fn`, `unsafe`, `extern`, identifier, `::`, `<`, square brackets, `*`, `&`, `!`, `impl`, `_`, lifetime")
```

Adding the `full` feature compiles successfully.

Would it be considered reasonable to enable const generics in this library (before https://github.com/dtolnay/syn/issues/264 lands) by doing the following? Perhaps gate it using a `nightly` feature?
```diff
diff --git a/Cargo.toml b/Cargo.toml
index ed9310a..a79edc1 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -24,8 +24,7 @@ unicode-xid = "0.2"

 [dependencies.syn]
 version = "1"
-default-features = false
-features = ["derive", "parsing", "printing", "clone-impls", "visit", "extra-traits"]
+features = ["full"]

 [dev-dependencies]
 # Used in the documentation as an example trait crate provider. Unfortunately,
```

**Comment by mystor** [comment]
I would prefer not to increase the required feature set from syn in order to add support for parsing const generics like this. synstructure intentionally keeps it's required feature set as small as possible to provide flexibility.

If a downstream crate wants to explicitly support the feature, it can use the additive property of features, and require the `["full"]` syn feature directly, without any changes to synstructure itself.

```toml
[dependencies]
synstructure = "0.12"
syn = { version = "1.0", features = ["full"] }
```

**Comment by nhynes** [comment]
right, in retrospect I should have considered that considering that only one version of a crate is used 🤦. thanks
