### ISSUE TITLE
Cannot document derive macros with decl_derive

### ISSUE THREAD

**Issue by nox** [mystor/synstructure#46]
This is probably true of the other helper macros too.

**Comment by mystor** [comment]
I think this is a dup of #21, it should be possible since #35, with the following syntax:

```rust
decl_derive! {
    [Interesting] =>
    /// Documentation Comments
    derive_interesting
}
```

**Comment by nox** [comment]
Oh sorry I put the docs over the bracketed thing. Thanks for the answer!
