### ISSUE TITLE
Support for derive on unions?

### ISSUE THREAD

**Issue by mystor** [mystor/synstructure#6]
I don't know what the correct behavior for synstructure should be here. In the update for syn 0.12, I intend to simply panic when being passed a union.

We should figure out what to do in that situation.

**Comment by dtolnay** [comment]
I expect most custom derives will not handle unions and just panic. I included them in DeriveInput because the compiler permits derive on unions. Something like [`typename_derive`](https://github.com/strymon-system/typename) will want to support them.

**Comment by mystor** [comment]
Yeah, that seems like the most reasonable solution, at least for now.

**Comment by joshlf** [comment]
Now that syn supports `Error::to_compiler_error`, perhaps the error could be formatted using that instead of panicking? It'd also be cool if unions were supported - I'm working on a custom derive that I suspect will have consumers at some point that use unions.

**Comment by mystor** [comment]
synstructure was changed to use `Error::to_compiler_error` in #28, and handling unions generically probably isn't a good idea. Closing this issue.

**Comment by joshlf** [comment]
> and handling unions generically probably isn't a good idea

I'm curious what the thinking is here? Do you mean handling unions at all, or does the word "generically" here mean something specific? The reason I ask is that I'd like to be able to support unions in my custom derive at some point. I can use something other than synstructure, of course - I just mean to illustrate that there are real use cases.

**Comment by mystor** [comment]
Support for custom derives on unions was added in https://github.com/rust-lang/rust/pull/50383 for consistency with built-in derives, despite most derives not being compatible (https://github.com/rust-lang/rust/pull/50383#issuecomment-386091557). This is because union field accesses are unsafe, and the correctness of these accesses depends on external logic not visible to the derive implementer.

In effect, a derive which cares about the values of fields cannot support unions, which vastly limits the set of compatible derives. Only specific derives, such as the built-in `#[derive(Copy, Clone)]`, can support unions, and derives which can won't benefit from synstructure, which provides helpers for matching against and accessing fields.

**Comment by mystor** [comment]
> The reason I ask is that I'd like to be able to support unions in my custom derive at some point. I can use something other than synstructure, of course - I just mean to illustrate that there are real use cases.

If there are specific synstructure features which would be useful for your `union` derives, I'd be interested to hear about them. It may be worthwhile decoupling them from the `Structure` type, so that they can be supported there too. Perhaps another type which doesn't provide access to pattern matching or field information could be useful for traits which want to support `union` as well, which makes it clear that variant values, etc, are not available.

**Comment by joshlf** [comment]
Concretely, I'm interested in deriving the [zerocopy](https://docs.rs/zerocopy) traits, which are just unsafe marker traits that don't actually produce any code. For example, a derive of [FromBytes](https://docs.rs/zerocopy/0.2.8/zerocopy/trait.FromBytes.html) for a union would just need to decide whether each individual variant was itself `FromBytes`. The utility is certainly limited compared to types where field access isn't unsafe, but it's still helpful (for example, to implement variable-length POSIX API structs).

The part of synstructure that we currently make use of is `decl_derive!`: https://docs.rs/zerocopy-derive/0.1.4/src/zerocopy_derive/lib.rs.html#38.

**Comment by mystor** [comment]
I didn't see any uses of `Structure` other than to extract the `.ast()` field. This `DeriveInput` object is easy to get with only `syn`, so it'd probably be best to just use it directly:

```rust
#[proc_macro_derive(FromBytes)]
pub fn derive_from_bytes(ts: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let ast = syn::parse_macro_input!(ts as DeriveInput);
    match &ast.data {
        Data::Struct(strct) => derive_from_bytes_struct(&ast, strct),
        Data::Enum(enm) => derive_from_bytes_enum(&ast, enm),
        Data::Union(uni) => derive_from_bytes_union(&ast, uni),
    }
}
```

**Comment by joshlf** [comment]
Ah you're probably right. It's been a while since I wrote the code, so I honestly don't remember why I used synstructure. Certainly looks like, whatever the reason, we don't need it anymore.
